### ISSUE TITLE
Introduct GoReleaser

### ISSUE THREAD

**Issue by davideimola** [Wabri/Daje#17]
Introduct GoReleaser for Continuous Integration and Delivery.

We want to deliver in few different ways:

- Linux (deb and rpm)
- MacOS
- Windows

**Comment by AugustasV** [comment]
I would like to work on it!

**Comment by davideimola** [comment]
Ok @AugustasV! Let me know if you need something!

BTW the project does not have anything at the moment as we have to start working on it but this issue is fine :D
